import argparse
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-we', '--wandb_entity', type=str, default='cs24m041')
    parser.add_argument('-wp', '--wandb_project', type=str, default='6401_Assignment1')
    parser.add_argument('-d', '--dataset', type=str, default='fashion_mnist',choices=["mnist", "fashion_mnist"])
    parser.add_argument('-e', '--epochs', type=int, default=14)
    parser.add_argument('-b', '--batch_size', type=int, default=64)
    parser.add_argument('-l', '--loss', type=str, default='cross_entropy',choices=["mean_squared_error", "cross_entropy"])
    parser.add_argument('-o', '--optimizer', type=str, default='adam',choices=["sgd", "momentum", "nag", "rmsprop", "adam", "nadam"])
    parser.add_argument('-w_i', '--weight_init', type=str, default='Xavier',choices=["random", "Xavier"])
    parser.add_argument('-lr', '--learning_rate', type=float, default=0.001)
    parser.add_argument('-m', '--momentum', type=float, default=0.9)
    parser.add_argument('-beta', '--beta', type=float, default=0.9)
    parser.add_argument('-beta1', '--beta1', type=float, default=0.9)
    parser.add_argument('-beta2', '--beta2', type=float, default=0.999)
    parser.add_argument('-eps', '--epsilon', type=float, default=0.000001)
    parser.add_argument('-w_d', '--weight_decay', type=float, default=0)
    parser.add_argument('-nhl', '--num_layers', type=int, default=4)
    parser.add_argument('-sz', '--hidden_size', type=int, default=128)
    parser.add_argument('-a', '--activation', type=str, default='ReLU',choices=['sigmoid', 'ReLU', 'tanh'])
    return parser.parse_args()

